server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/order-server?useSSL=false
    username: root
    password:
    driver-class-name: com.mysql.jdbc.Driver
  application:
    name: order-service
  cloud:
    nacos:
      server-addr: 192.168.102.55:8848
      discovery:
        cluster-name: local-group
mybatis:
  type-aliases-package: cn.itcast.user.pojo
  configuration:
    map-underscore-to-camel-case: true
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS
logging:
  config: classpath:logback-spring.xml
  level:
    root: info
