server:
  port: 8083
spring:
  datasource:
    url: jdbc:mysql://192.168.102.206:3306/userDB?useSSL=false
    username: userserver
    password: userserver
    driver-class-name: com.mysql.jdbc.Driver
mybatis:
  type-aliases-package: cn.itcast.user.pojo
  configuration:
    map-underscore-to-camel-case: true
logging:
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS
