server:
  port: 10010
spring:
  application:
    name: gateway-service
  cloud:
    nacos:
      server-addr: 192.168.102.55:8848
    gateway:
#      定义路由规则
      routes:
        - id: user-service
          uri: lb://user
          predicates:
             - Path=/user/**
        - id: order-service
          uri: lb://order-service
          predicates:
#             定义匹配规则
             - Path=/order/**
          filters:
             - AddRequestHeader=CustomRequestHeader,This is AddRequestHeader Filter-Component
